# Generated by Django 4.2.8 on 2024-03-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_cd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.IntegerField(verbose_name='apiID')),
                ('date_week', models.BooleanField(verbose_name='일간 or 주간')),
                ('rank', models.IntegerField(verbose_name='순위')),
                ('name', models.TextField(verbose_name='영화제목')),
                ('date', models.DateField(verbose_name='요청날짜')),
                ('audi_cnt', models.IntegerField(verbose_name='관객수')),
                ('audi_acc', models.IntegerField(verbose_name='누적관객수')),
                ('thumbnail', models.TextField(verbose_name='thumbnail')),
            ],
        ),
    ]
