# Generated by Django 4.2.8 on 2024-03-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.TextField(blank=True, verbose_name='thumbnail'),
        ),
    ]
