# Generated by Django 4.2.8 on 2024-02-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_movies',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='movies.movie', verbose_name='좋아요 누른 Movie 목록'),
        ),
    ]
